# Generated by Django 5.2.7 on 2025-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_college',
            name='COLLEGE_LOGO',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_CURRENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_DATE_OF_BIRTH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_GITHUB_LINK',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_LINKEDIN_URL',
            field=models.URLField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_PERMANENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_PERSONAL_WEBSITE_PORTFOLIO',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_PHONE_NO',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
