# Generated by Django 5.2.7 on 2025-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0002_alter_tbl_college_college_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_college',
            name='COLLEGE_ESTABLISHED_YEAR',
            field=models.IntegerField(),
        ),
    ]
