# Generated by Django 5.2.7 on 2025-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0003_alter_tbl_college_college_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_admin',
            name='ROLE_TYPE',
            field=models.CharField(default='ADMIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='ROLE_TYPE',
            field=models.CharField(default='COMPANY', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='ROLE_TYPE',
            field=models.CharField(default='STUDENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='ROLE_TYPE',
            field=models.CharField(default='TNP MEMBER', max_length=50),
        ),
    ]
