# Generated by Django 5.2.7 on 2025-10-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0004_alter_tbl_admin_role_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tnp',
            name='COLLEGE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
    ]
