# Generated by Django 5.2.7 on 2025-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0005_alter_tbl_tnp_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_admin',
            name='ADMIN_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/admin/'),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='COMPANY_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/company/'),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/student/'),
        ),
        migrations.AlterField(
            model_name='tbl_tnp',
            name='TNP_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/tnp/'),
        ),
    ]
