# Generated by Django 5.2.7 on 2025-10-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0006_alter_tbl_admin_admin_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='STUDENT_ROLL_NO',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_PROFILE_PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/tnp/'),
        ),
    ]
