# Generated by Django 5.2.7 on 2025-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0007_tbl_student_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='COMPANY_DATE_OF_ESTABLISHMENT',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='COMPANY_LINKEDIN_URL',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_company',
            name='COMPANY_PERMANENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
