# Generated by Django 5.2.7 on 2025-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0008_alter_tbl_company_company_date_of_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_AREA_OF_INTEREST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_BACKLOG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_BRANCH',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_COURSE',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_CURRENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_CURRENT_SEMSETER',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_DATE_OF_BIRTH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_ENROLLMENT_NUMBER',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_GENDER',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_GITHUB_LINK',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_LINKEDIN_URL',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_PERCENTAGE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_PERMANENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_RESUME',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_SOFT_SKILLS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_TECHNICAL_SKILLS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='STUDENT_YEAR_OF_PASSING',
            field=models.DateField(blank=True, null=True),
        ),
    ]
