# Generated by Django 5.2.7 on 2025-10-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0009_alter_tbl_student_student_area_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_internship',
            name='COMPANY',
            field=models.CharField(max_length=255),
        ),
    ]
