# Generated by Django 5.2.7 on 2025-10-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0010_alter_tbl_internship_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_job',
            name='JOB_VACANCY',
            field=models.IntegerField(default=0),
        ),
    ]
