# Generated by Django 5.2.7 on 2025-10-26 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0011_tbl_job_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_interview_schedule',
            name='COLLEGE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
        migrations.AddField(
            model_name='tbl_interview_schedule',
            name='COMPANY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_placement_round',
            name='COLLEGE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
        migrations.AddField(
            model_name='tbl_placement_round',
            name='COMPANY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_quiz',
            name='COLLEGE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
        migrations.AddField(
            model_name='tbl_quiz',
            name='COMPANY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_round_result',
            name='COLLEGE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
        migrations.AddField(
            model_name='tbl_round_result',
            name='COMPANY',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company'),
        ),
        migrations.AddField(
            model_name='tbl_round_result',
            name='JOB',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job'),
        ),
        migrations.AlterField(
            model_name='tbl_interview_schedule',
            name='APPLICATION',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_application'),
        ),
        migrations.AlterField(
            model_name='tbl_interview_schedule',
            name='ROUND',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_placement_round'),
        ),
        migrations.AlterField(
            model_name='tbl_placement_round',
            name='JOB',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job'),
        ),
        migrations.AlterField(
            model_name='tbl_quiz',
            name='JOB',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job'),
        ),
        migrations.AlterField(
            model_name='tbl_round_result',
            name='INTERVIEW',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_interview_schedule'),
        ),
        migrations.AlterField(
            model_name='tbl_round_result',
            name='STUDENT',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_student'),
        ),
        migrations.CreateModel(
            name='TBL_CODING_QUESTION',
            fields=[
                ('QUESTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('QUESTION_TITLE', models.CharField(max_length=100)),
                ('QUESTION_DESCRIPTION', models.TextField()),
                ('DIFFICULTY', models.CharField(max_length=50)),
                ('DURATION_MINUTES', models.IntegerField()),
                ('COLLEGE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college')),
                ('COMPANY', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company')),
                ('JOB', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_GD_GROUP',
            fields=[
                ('GROUP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GROUP_NUMBER', models.IntegerField()),
                ('SCHEDULE', models.DateTimeField()),
                ('MEETING_LINK', models.CharField(blank=True, max_length=255, null=True)),
                ('COLLEGE', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college')),
                ('COMPANY', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company')),
                ('JOB', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_GD_GROUP_MEMBER',
            fields=[
                ('GROUP_MEMBER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GROUP', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_gd_group')),
                ('STUDENT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_student')),
            ],
        ),
    ]
