# Generated by Django 5.2.7 on 2025-10-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0014_tbl_round_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_CHAT_ROOM',
            fields=[
                ('ROOM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IS_GLOBAL', models.BooleanField(default=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='HIRE.tbl_college')),
                ('USER_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1', to='HIRE.tbl_user')),
                ('USER_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2', to='HIRE.tbl_user')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'TBL_CHAT_ROOM',
                'unique_together': {('COLLEGE', 'USER_1', 'USER_2')},
            },
        ),
        migrations.CreateModel(
            name='TBL_CHAT_MESSAGE',
            fields=[
                ('MESSAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MESSAGE', models.TextField()),
                ('SENT_AT', models.DateTimeField(auto_now_add=True)),
                ('IS_READ', models.BooleanField(default=False)),
                ('RECEIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='HIRE.tbl_user')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='HIRE.tbl_user')),
                ('ROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='HIRE.tbl_chat_room')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'TBL_CHAT_MESSAGE',
                'ordering': ['SENT_AT'],
            },
        ),
        migrations.DeleteModel(
            name='TBL_CHAT',
        ),
    ]
