# Generated by Django 5.2.7 on 2025-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0015_tbl_chat_room_tbl_chat_message_delete_tbl_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat_message',
            name='FILE',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
