# Generated by Django 5.2.7 on 2025-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0016_tbl_chat_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_placement_round',
            name='ROUND_DURATION',
            field=models.IntegerField(default=0),
        ),
    ]
