# Generated by Django 5.2.7 on 2025-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0017_tbl_placement_round_round_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_quiz',
            name='QUIZ_PASS',
            field=models.IntegerField(default=1),
        ),
    ]
