# Generated by Django 5.2.7 on 2025-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0018_tbl_quiz_quiz_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_quiz',
            name='QUIZ_END_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tbl_quiz',
            name='QUIZ_START_DATE',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
