# Generated by Django 5.2.7 on 2025-10-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0019_tbl_quiz_quiz_end_date_tbl_quiz_quiz_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student_answer',
            name='JOB',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job'),
        ),
        migrations.AddField(
            model_name='tbl_student_answer',
            name='QUIZ_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_quiz'),
        ),
    ]
