# Generated by Django 5.2.7 on 2025-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0022_alter_tbl_round_result_round_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_application',
            name='APPLICATION_STATUS',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Aptitude', 'Aptitude Round'), ('Technical/GD', 'Technical / Group Discussion'), ('Technical Interview', 'Technical Interview'), ('HR Interview', 'HR Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Completed', 'Process Completed')], default='Applied', max_length=50),
        ),
    ]
