# Generated by Django 5.2.7 on 2025-10-29 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0023_alter_tbl_application_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_gd_group',
            options={'ordering': ['GROUP_NUMBER']},
        ),
        migrations.AddField(
            model_name='tbl_gd_group',
            name='CREATED_AT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tbl_gd_group',
            name='ROUND',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_placement_round'),
        ),
        migrations.AddField(
            model_name='tbl_gd_group_member',
            name='JOINED_AT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group',
            name='COLLEGE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_college'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group',
            name='COMPANY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_company'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group',
            name='GROUP_NUMBER',
            field=models.IntegerField(help_text='Group number for this GD session (e.g., 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group',
            name='JOB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_job'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group',
            name='SCHEDULE',
            field=models.DateTimeField(help_text='Date & time of the GD session'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group_member',
            name='GROUP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='HIRE.tbl_gd_group'),
        ),
        migrations.AlterField(
            model_name='tbl_gd_group_member',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HIRE.tbl_student'),
        ),
        migrations.AlterUniqueTogether(
            name='tbl_gd_group',
            unique_together={('JOB', 'GROUP_NUMBER')},
        ),
        migrations.AlterUniqueTogether(
            name='tbl_gd_group_member',
            unique_together={('GROUP', 'STUDENT')},
        ),
    ]
