# Generated by Django 5.2.7 on 2025-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0024_alter_tbl_gd_group_options_tbl_gd_group_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_gd_group',
            name='STATUS',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Link Sent', 'Link Sent')], default='Pending', max_length=20),
        ),
    ]
