# Generated by Django 5.2.7 on 2025-10-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0025_tbl_gd_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_interview_schedule',
            name='INTERVIEW_MODE',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_interview_schedule',
            name='INTERVIEW_STATUS',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
    ]
