# Generated by Django 5.2.7 on 2025-10-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0026_alter_tbl_interview_schedule_interview_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_file_storage',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='tbl_job_skills',
            name='JOB',
        ),
        migrations.RemoveField(
            model_name='tbl_placement_result_summary',
            name='JOB',
        ),
        migrations.RemoveField(
            model_name='tbl_placement_result_summary',
            name='STUDENT',
        ),
        migrations.RemoveField(
            model_name='tbl_round_evaluation',
            name='EVALUATOR',
        ),
        migrations.RemoveField(
            model_name='tbl_round_evaluation',
            name='RESULT',
        ),
        migrations.RemoveField(
            model_name='tbl_student_skills',
            name='STUDENT',
        ),
        migrations.RemoveField(
            model_name='tbl_internship',
            name='INTERNSHIP_DURATION',
        ),
        migrations.DeleteModel(
            name='TBL_ACTIVITY_LOG',
        ),
        migrations.DeleteModel(
            name='TBL_FILE_STORAGE',
        ),
        migrations.DeleteModel(
            name='TBL_JOB_SKILLS',
        ),
        migrations.DeleteModel(
            name='TBL_PLACEMENT_RESULT_SUMMARY',
        ),
        migrations.DeleteModel(
            name='TBL_ROUND_EVALUATION',
        ),
        migrations.DeleteModel(
            name='TBL_STUDENT_SKILLS',
        ),
    ]
