# Generated by Django 5.2.7 on 2025-10-30 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0027_remove_tbl_file_storage_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbl_chat_room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='COLLEGE',
        ),
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='USER_1',
        ),
        migrations.RemoveField(
            model_name='tbl_chat_room',
            name='USER_2',
        ),
        migrations.RenameField(
            model_name='tbl_email_verification',
            old_name='IS_VERIFIED',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='tbl_email_verification',
            old_name='USER',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_email_verification',
            name='EXPIRES_AT',
        ),
        migrations.RemoveField(
            model_name='tbl_email_verification',
            name='OTP_CODE',
        ),
        migrations.RemoveField(
            model_name='tbl_email_verification',
            name='OTP_ID',
        ),
        migrations.AddField(
            model_name='tbl_email_verification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tbl_email_verification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_email_verification',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='tbl_email_verification',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='TBL_CHAT_MESSAGE',
        ),
        migrations.DeleteModel(
            name='TBL_CHAT_ROOM',
        ),
        migrations.AddField(
            model_name='tbl_email_verification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
