# Generated by Django 5.2.7 on 2025-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HIRE', '0028_alter_tbl_chat_room_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_education',
            name='CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
